/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bugy
 */
public class DialogOwners extends javax.swing.JDialog {

    private boolean cancel = true;
    private DefaultTableModel dtm;
    private JsonObject owners;

    /**
     * Creates new form DialogOwners
     */
    public DialogOwners(java.awt.Frame parent, boolean modal, JsonObject owners) {
        super(parent, modal);
        initComponents();
        dtm = new DefaultTableModel(0, 0);
        this.owners = owners;
        fillData();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOwnerships = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Rodné číslo:");

        jLabel2.setText("Podiel v % :");

        jTableOwnerships.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableOwnerships);

        jLabel21.setText("Ostatné podiely majiteľov");

        jButton2.setText("zruš");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double sum = Double.parseDouble(jTextField11.getText().replace(',', '.'));
        ArrayList<Double> shareArr = new ArrayList<>();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            String result = Main.tryParseToDouble(dtm.getValueAt(i, 1).toString());
            if (result != null) {
                JOptionPane.showMessageDialog(this,
                        result,
                        "Pozor",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            Double share = Double.parseDouble(dtm.getValueAt(i, 1).toString().replace(',', '.'));
            shareArr.add(share);
            sum += share;
        }

        if (sum != 100.0) {
            JOptionPane.showMessageDialog(this,
                    "Suma podielov musí byť 100%",
                    "Pozor",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        ArrayList<String> rcArr = new ArrayList<>();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            rcArr.add(dtm.getValueAt(i, 0).toString());
        }

        fillResponsData(shareArr, rcArr);
        cancel = false;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean isCancel() {
        return cancel;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOwnerships;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    // End of variables declaration//GEN-END:variables

    private void fillData() {
        jTextField1.setEnabled(false);
        jTextField11.setEnabled(false);

        if (owners != null && owners.get("editedOwner") != null) {
            this.jTextField1.setText(owners.get("editedOwner").getAsJsonObject().get("rc").getAsString());
            this.jTextField11.setText(owners.get("editedOwner").getAsJsonObject().get("share").getAsString());
        }
        String[] header = new String[]{"Rodné čislo", "Podiel v %"};
        dtm.setColumnIdentifiers(header);
        jTableOwnerships.setModel(dtm);
        if (owners != null && owners.get("ownerships") != null) {
            for (JsonElement jsonElement : owners.get("ownerships").getAsJsonArray()) {
                JsonObject owner = (JsonObject) jsonElement;
                dtm.addRow(new Object[]{owner.get("rc").getAsString(), owner.get("share").getAsString()});
            }
        }
    }

    private void fillResponsData(ArrayList<Double> arrDouble, ArrayList<String> rcArr) {
        JsonArray jsonArray = new JsonArray();
        owners.get("editedOwner").getAsJsonObject().addProperty("share", Double.parseDouble(jTextField11.getText().replace(',', '.')));
        for (int i = 0; i < arrDouble.size(); i++) {
            JsonObject jo = new JsonObject();
            jo.addProperty("rc", rcArr.get(i));
            jo.addProperty("share", arrDouble.get(i));
            jsonArray.add(jo);
        }
        owners.add("ownerships", jsonArray);
    }

    public JsonObject getOwners() {
        return owners;
    }
}
